version: 2.1
jobs:
  test:
    parameters:
      python_version:
        description: "The Python version to use for running the tests"
        type: string
    docker:
      - image: cimg/python:<< parameters.python_version >>
        environment:
          TEST_STORAGE_FILE_URI: file:///tmp/integration-tests
          TEST_STORAGE_FTP_URI: ftp://files:password@localhost/integration-tests
          # TEST_STORAGE_GS_URI in CircleCI context
          # TEST_STORAGE_S3_URI in CircleCI context
      - image: onjin/alpine-vsftpd:latest
        environment:
          PASSWORD: password
        command: >
          sh -c
          "sed -i -e 's#/home/./files#/home/files/./#' /etc/passwd;
          echo 'allow_writeable_chroot=YES' >> /etc/vsftpd/vsftpd.conf;
          /docker-entrypoint.sh"

    steps:
      - checkout

      - run:
          name: Save Python Version
          command: |
            python --version > pythonversion

      - restore_cache:
          keys:
            - v1-python-{{ checksum "pythonversion" }}-dependencies-{{ checksum "poetry.lock" }}

      - run:
          name: install dependencies
          command: |
            poetry self update --no-ansi -- 1.8.4
            poetry install --no-ansi

            mkdir -p test-reports

      - save_cache:
          paths:
            - ~/.cache/pypoetry/virtualenvs
          key: v1-python-{{ checksum "pythonversion" }}-dependencies-{{ checksum "poetry.lock" }}

      - run:
          name: run tests
          command: |
            poetry run pytest --verbose --junit-xml=test-reports/pytest.xml

      - run:
          name: run linter
          command: |
            poetry run flake8 | tee test-reports/flake8-errors

      - run:
          name: run typechecks
          command: |
            poetry run mypy --junit-xml=test-reports/mypy.xml

      - store_artifacts:
          path: test-reports
          prefix: python-<< parameters.python_version >>

      - store_test_results:
          path: test-reports
          prefix: python-<< parameters.python_version >>

  publish:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Publish to PyPI
          command: |
            export POETRY_HTTP_BASIC_PYPI_USERNAME=$PYPI_USERNAME
            export POETRY_HTTP_BASIC_PYPI_PASSWORD=$PYPI_PASSWORD

            poetry publish --build

workflows:
  version: 2
  test-and-build:
    jobs:
      - test:
          name: test-3.6
          python_version: "3.6"
          filters:
            tags:
              only: /.*/
          context: storage-library-tester
      - test:
          name: test-3.7
          python_version: "3.7"
          filters:
            tags:
              only: /.*/
          context: storage-library-tester
      - publish:
          requires:
            - test-3.6
            - test-3.7
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*.*/
            branches:
              ignore: /.*/
          context: storage-library-publisher
